name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-tests:
    env:
      UV_SYSTEM_PYTHON : true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
        python-version: "3.10"

    - name: UV Sync
      run: |
        uv sync

    - name: Run pytest
      run: |
        uv tool install pytest
        uvx --frozen pytest
