name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
        python-version: "3.10"

    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives/*.deb
        key: apt-cache-${{ runner.os }}
        restore-keys: apt-cache-${{ runner.os }}

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
