name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v4
      with:
        python-version: "3.10"

    - name: Run pytest
      run: |
        uv tool install pytest
        uv run pytest
